# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160604_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
