# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 22:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_fieldtype_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique='true', verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(max_length=5000, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only ascii characters can be used', regex='^[a-zA-Z0-9_]+$')], verbose_name='Системное имя'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='fieldtype',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, unique='true', verbose_name='Имя'),
        ),
    ]
