# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_modification_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='price',
        ),
    ]
