# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_modification_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='typeName',
            field=models.CharField(choices=[('integer', 'Int'), ('string', 'String'), ('float', 'Float')], max_length=50, null=True, verbose_name='type'),
        ),
    ]
