# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160725_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecimalFieldStorage',
            new_name='DecimalField',
        ),
        migrations.RenameModel(
            old_name='IntegerFieldStorage',
            new_name='IntegerField',
        ),
    ]
